services:
    _defaults:
        public: false

    Prooph\EventStore\EventStore: '@app.event_store.default'

    app.event_store.default:
        class: Prooph\EventStore\Pdo\PostgresEventStore
        arguments:
            - '@prooph_event_store.message_factory'
            - '@app.event_store.pdo_connection.postgres'
            - '@app.event_store.postgres.persistence_strategy'

    app.event_store.pdo_connection.postgres:
        class: PDO
        arguments:
            - '%env(POSTGRES_DNS)%'
            - '%env(POSTGRES_USER)%'
            - '%env(POSTGRES_PASSWORD)%'

    app.event_store.postgres.persistence_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\PostgresSingleStreamStrategy
